### ISSUE TITLE
Mustaches is not a constructor

### ISSUE THREAD

**Issue by Codetopher** [Errorname/google-docs-mustaches#54]
Using the latest version of this plugin, I tried executing the basic code.

```js 
import Mustaches from 'google-docs-mustaches'

const mustaches = new Mustaches({
  token: () => gapi.auth.getToken().access_token
})

// ID of the template
const source = '11rGORd6FRxOGERe7fh6LNQfyB48ZvOgQNH6GScK_FfA'

// ID of the destination folder
const destination = '18mcqwbaXS8NOqZjztB3OUQAc5_P8M6-l'

mustaches.interpolate({
  source,
  destination,
  data: {
    firstname: 'Thibaud',
    lastname: 'Courtoison',
    accounts: [{ money: 1500 }]
  }
})
```
This is the error that I encounter:
const mustaches = new Mustaches({
                  ^

TypeError: Mustaches is not a constructor
    at file:///C:/Programs/mustache.js:5:19
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

I am using node version 14.16.0.

**Comment by 8BitJonny** [comment]
Hi @Codetopher,
can you pls try 
```js
const mustaches = new Mustaches.default({
  token: () => gapi.auth.getToken().access_token
})
```

**Comment by Codetopher** [comment]
> Hi @Codetopher,
> can you pls try
> 
> ```js
> const mustaches = new Mustaches.default({
>   token: () => gapi.auth.getToken().access_token
> })
> ```
@8BitJonny 
After trying this, I no longer receive the error. Thank you for your help.

**Comment by 8BitJonny** [comment]
@Codetopher Glad that I could help

@Errorname Maybe the example code in the documentation should be updated accordingly
